spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_URL}?serverTimezone=UTC&characterEncoding=UTF-8&autoReconnection=true
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        ddl-auto: create-drop
        # ddl-auto : update
        # sql, 로그 표시
        show_sql: true
        format_sql: true
        use_sql_comments: true
service:
    url: http://localhost:${PORT}/url/

# hibernate log ? 값 표시
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace